import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const files = {
  '/': ['index.html', 'text/html; charset=utf-8'],
  '/app.js': ['app.js', 'text/javascript; charset=utf-8'],
  '/style.css': ['style.css', 'text/css; charset=utf-8'],
  '/class-icon.svg': ['class-icon.svg', 'image/svg+xml'],
  '/favicon.ico': ['class-icon.ico', 'image/x-icon', true],
};

export function embedUi() {
  const assets = {};
  for (const [route, [file, contentType, binary]] of Object.entries(files)) {
    const body = fs.readFileSync(path.join(root, 'public', file), binary ? undefined : 'utf8');
    if (binary ? !body.length : !body.trim()) throw new Error(`The UI asset is empty: ${file}`);
    assets[route] = { body: binary ? body.toString('base64') : body, contentType, ...(binary ? { base64: true } : {}) };
  }
  assets['/index.html'] = assets['/'];
  const target = path.join(root, 'build', 'generated', 'ui-assets.generated.js');
  fs.mkdirSync(path.dirname(target), { recursive: true });
  const temporary = `${target}.${process.pid}.tmp`;
  fs.writeFileSync(temporary, '// Generated by scripts/embed-ui.js. Edit public/ instead.\nexport const ASSETS = ' + JSON.stringify(assets) + ';\nfor (const asset of Object.values(ASSETS)) { if (asset.base64) { asset.body = Buffer.from(asset.body, "base64"); delete asset.base64; } }\n', 'utf8');
  fs.renameSync(temporary, target);
  return target;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  console.log(`Embedded browser UI: ${embedUi()}`);
}
